---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  labels:
    app.kubernetes.io/name: "hobby-frontend"
    app.kubernetes.io/version: "1.0.0"
  name: "hobby-frontend"
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app.kubernetes.io/name: "hobby-frontend"
    app.kubernetes.io/version: "1.0.0"
  name: "hobby-frontend"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "hobby-frontend"
    app.kubernetes.io/version: "1.0.0"
  type: "LoadBalancer"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app.kubernetes.io/name: "hobby-frontend"
    app.kubernetes.io/version: "1.0.0"
  name: "hobby-frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "hobby-frontend"
      app.kubernetes.io/version: "1.0.0"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "hobby-frontend"
        app.kubernetes.io/version: "1.0.0"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "quay.io/anasandbox/hobby-frontend:1.0.1-native"
        imagePullPolicy: "IfNotPresent"
        name: "hobby-frontend"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
      serviceAccount: "hobby-frontend"
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  name: hobby-frontend
  labels:
    app: hobby-frontend
spec:
  to:
    kind: Service
    name: hobby-frontend
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
status:
  ingress:
    - routerName: default
      conditions:
        - type: Admitted
          status: 'True'
      wildcardPolicy: None
