apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: activity
spec:
  host: activity
  trafficPolicy:
    loadBalancer:
      simple: activity
  subsets:
  - labels:
      version: v1
    name: version-v1
  - labels:
      version: v2
    name: version-v2
---