apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: activity
spec:
  hosts:
    - "*"
  gateways:
    - activity-gateway
  http:
    - route:
        - destination:
            host: activity
            subset: version-v1
      mirror:
        host: activity
        subset: version-v2
---