apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: activity
spec:
  hosts:
    - "*"
  gateways:
    - activity-gateway
  http:
    - route:
        - destination:
            host: activity
      retries:
        attempts: 4
        retryOn: retriable-4xx
---