apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: activity
spec:
  hosts:
    - "*"
  gateways:
    - activity-gateway
  http:
    - match:
        - headers:
            baggage-user-agent:
              regex: .*Safari.*
      route:
        - destination:
            host: activity
            subset: version-v1
    - route:
        - destination:
            host: activity
            subset: version-v2
---
